site_name: Operating Systems (H) 2020 Spring
repo_name: OSH-2020/OSH-2020.github.io
repo_url: https://github.com/OSH-2020/OSH-2020.github.io

theme:
  name: 'material'
  language: 'zh'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - toc:
      permalink: true

extra_css:
  # Borrow CSS from Linux 101
  - 'https://101.ustclug.org/css/extra.css'

nav:
  - 首页: README.md
  - 大作业: x/README.md
  - 实验一:
    - 介绍: lab-1/README.md
    - Linux 的安装与使用: lab-1/linux/README.md
    - 学习使用 Git: lab-1/git/README.md
    - 学习 GitHub 的简单使用，搭建实验私有仓库: lab-1/github/README.md
    - 编译 Linux 内核并在 QEMU 中测试: lab-1/kernel/README.md
    - 构建初始内存盘 (initrd, init ram disk): lab-1/initrd/README.md
    - 使用汇编语言，编写 x86 裸金属 (bare-metal) 程序: lab-1/mbr/README.md
  - 实验二: lab-2/README.md
  - 实验三: lab-3/README.md
  - 实验四:
    - 介绍: lab-4/README.md
    - 准备 rootfs: lab-4/rootfs/README.md
    - 挂载文件系统: lab-4/mounts/README.md
    - 使用 pivot_root: lab-4/pivot_root/README.md
    - 限制 capabilities: lab-4/capabilities/README.md
    - 过滤系统调用: lab-4/seccomp/README.md
    - 限制系统资源: lab-4/cgroup/README.md
  - FAQ: faq/README.md
